import type { Event, Testimonial, FAQ, Product, Class, Order } from "@/types";

export const mockEvents: Event[] = [
  {
    id: "1", created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    title: "Torneo Verano PPC 2026", slug: "torneo-verano-2026",
    description: "El torneo más esperado del año. Categorías A, B y C. Premios para todos los ganadores y cena de clausura.",
    content: null, image_url: "https://placehold.co/800x500/0A0A0A/22C55E?text=Torneo+Verano",
    event_date: "2026-06-15T09:00:00Z", event_end_date: "2026-06-16T20:00:00Z",
    location: "Padel Pro Club", category: "tournament", price: 35000,
    max_participants: 64, current_participants: 48,
    registration_url: null, is_active: true, is_featured: true, metadata: null,
  },
  {
    id: "2", created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    title: "Noche de Pádel + BBQ", slug: "noche-padel-bbq",
    description: "Jornada social con partidos mixtos, BBQ y música. Ven con tu pareja o te asignamos una.",
    content: null, image_url: "https://placehold.co/800x500/22C55E/0A0A0A?text=Noche+BBQ",
    event_date: "2026-07-08T19:00:00Z", event_end_date: "2026-07-08T23:00:00Z",
    location: "Padel Pro Club", category: "social", price: 15000,
    max_participants: 40, current_participants: 22,
    registration_url: null, is_active: true, is_featured: true, metadata: null,
  },
  {
    id: "3", created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    title: "Clínica con Pro", slug: "clinica-pro-marzo",
    description: "Aprende técnicas avanzadas con jugadores de nivel profesional. Cupos limitados.",
    content: null, image_url: "https://placehold.co/800x500/111111/FFFFFF?text=Clinica+Pro",
    event_date: "2026-08-22T10:00:00Z", event_end_date: "2026-08-22T14:00:00Z",
    location: "Cancha Central", category: "clinic", price: 45000,
    max_participants: 16, current_participants: 10,
    registration_url: null, is_active: true, is_featured: false, metadata: null,
  },
];

export const mockTestimonials: Testimonial[] = [
  { id: "1", created_at: new Date().toISOString(), author_name: "Andrés Morales", author_role: "Socio desde 2023", author_image: null, content: "El mejor club de la ciudad sin duda. Las canchas son de primera, el ambiente increíble y la organización de torneos es impecable.", rating: 5, is_active: true, sort_order: 1 },
  { id: "2", created_at: new Date().toISOString(), author_name: "Valentina Soto", author_role: "Alumna Academia", author_image: null, content: "Empecé desde cero en la academia y en 3 meses ya estoy jugando torneos. Los instructores son extraordinarios.", rating: 5, is_active: true, sort_order: 2 },
  { id: "3", created_at: new Date().toISOString(), author_name: "Rodrigo Peña", author_role: "Socio desde 2022", author_image: null, content: "Llevo 2 años jugando aquí y nunca me ha fallado. La app de reservas funciona perfecto y siempre hay disponibilidad.", rating: 5, is_active: true, sort_order: 3 },
  { id: "4", created_at: new Date().toISOString(), author_name: "Carolina López", author_role: "Jugadora competitiva", author_image: null, content: "Las canchas de indoor son las mejores que he jugado en Chile. Iluminación perfecta, superficie excelente.", rating: 5, is_active: true, sort_order: 4 },
];

export const mockFAQs: FAQ[] = [
  { id: "1", created_at: new Date().toISOString(), question: "¿Cómo reservo una cancha?", answer: "Puedes reservar a través de nuestra app oficial o en el link de reservas de la web. También puedes llamarnos o escribirnos por WhatsApp.", category: "reservas", sort_order: 1, is_active: true },
  { id: "2", created_at: new Date().toISOString(), question: "¿Con cuánta anticipación puedo reservar?", answer: "Puedes reservar hasta 7 días de anticipación. Los socios premium tienen acceso preferente con 10 días de anticipación.", category: "reservas", sort_order: 2, is_active: true },
  { id: "3", created_at: new Date().toISOString(), question: "¿Qué pasa si necesito cancelar?", answer: "Puedes cancelar sin costo hasta 4 horas antes. Cancelaciones tardías tienen un cargo del 50%.", category: "reservas", sort_order: 3, is_active: true },
  { id: "4", created_at: new Date().toISOString(), question: "¿Tienen equipamiento para arrendar?", answer: "Sí, tenemos palas y pelotas disponibles para arriendo en recepción por un valor de $5.000 por sesión.", category: "instalaciones", sort_order: 4, is_active: true },
  { id: "5", created_at: new Date().toISOString(), question: "¿Ofrecen clases para niños?", answer: "Sí, tenemos academia infantil desde los 6 años. Contáctanos para conocer horarios y disponibilidad.", category: "clases", sort_order: 5, is_active: true },
  { id: "6", created_at: new Date().toISOString(), question: "¿Tienen estacionamiento?", answer: "Sí, contamos con estacionamiento gratuito con capacidad para 40 vehículos. Acceso por Calle Lateral.", category: "instalaciones", sort_order: 6, is_active: true },
];

export const mockProducts: Product[] = [
  { id: "1", created_at: new Date().toISOString(), updated_at: new Date().toISOString(), name: "Paletero Oficial PPC", slug: "paletero-oficial-ppc", description: "Paletero premium con espacio para 2 palas, bolsillo para ropa y refuerzo impermeable.", price: 49900, compare_at_price: 59900, images: ["https://placehold.co/600x600/0A0A0A/22C55E?text=Paletero"], category: "accesorios", tags: ["paletero", "premium"], is_active: true, is_featured: true, stock_quantity: 20, sku: null, metadata: null },
  { id: "2", created_at: new Date().toISOString(), updated_at: new Date().toISOString(), name: "Camiseta Técnica PPC", slug: "camiseta-tecnica-ppc", description: "Camiseta técnica de alta transpiración con logo bordado. Material 100% poliéster reciclado.", price: 24900, compare_at_price: null, images: ["https://placehold.co/600x600/22C55E/0A0A0A?text=Camiseta"], category: "ropa", tags: ["camiseta"], is_active: true, is_featured: true, stock_quantity: 50, sku: null, metadata: null },
  { id: "3", created_at: new Date().toISOString(), updated_at: new Date().toISOString(), name: "Grip Pro Pack x3", slug: "grip-pro-pack-x3", description: "Pack de 3 grips premium antideslizantes. Absorción de sudor máxima.", price: 12900, compare_at_price: null, images: ["https://placehold.co/600x600/111111/FFFFFF?text=Grip+x3"], category: "accesorios", tags: ["grip"], is_active: true, is_featured: false, stock_quantity: 100, sku: null, metadata: null },
  { id: "4", created_at: new Date().toISOString(), updated_at: new Date().toISOString(), name: "Gorra PPC Edition", slug: "gorra-ppc-edition", description: "Gorra de tela técnica con visera curva. Logo del club bordado. Talla única.", price: 19900, compare_at_price: null, images: ["https://placehold.co/600x600/0A0A0A/FFFFFF?text=Gorra"], category: "accesorios", tags: ["gorra"], is_active: true, is_featured: false, stock_quantity: 30, sku: null, metadata: null },
];

export const mockClasses: Class[] = [
  { id: "1", created_at: new Date().toISOString(), name: "Academia Principiantes", slug: "academia-principiantes", description: "Aprende las bases del pádel desde cero. Sin experiencia previa necesaria.", level: "beginner", instructor: "María González", instructor_bio: null, instructor_image: null, schedule: [{ day: "Lunes", time: "09:00" }, { day: "Miércoles", time: "09:00" }], duration_minutes: 60, price_per_session: 12000, price_monthly: 45000, max_students: 8, image_url: null, is_active: true, is_featured: true, metadata: null },
  { id: "2", created_at: new Date().toISOString(), name: "Intermedio — Técnica y Táctica", slug: "intermedio-tecnica-tactica", description: "Mejora tu técnica y aprende tácticas para partidos competitivos.", level: "intermediate", instructor: "Carlos Ruiz", instructor_bio: null, instructor_image: null, schedule: [{ day: "Martes", time: "19:00" }, { day: "Jueves", time: "19:00" }], duration_minutes: 90, price_per_session: 18000, price_monthly: 65000, max_students: 6, image_url: null, is_active: true, is_featured: true, metadata: null },
  { id: "3", created_at: new Date().toISOString(), name: "Alto Rendimiento", slug: "alto-rendimiento", description: "Para jugadores avanzados que buscan competir. Trabajo físico y mental.", level: "advanced", instructor: "Diego Fernández", instructor_bio: null, instructor_image: null, schedule: [{ day: "Lunes", time: "07:00" }, { day: "Miércoles", time: "07:00" }, { day: "Viernes", time: "07:00" }], duration_minutes: 120, price_per_session: 25000, price_monthly: 90000, max_students: 4, image_url: null, is_active: true, is_featured: false, metadata: null },
];

export const mockOrders: Order[] = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    customer_email: "carlos.mendez@email.com",
    customer_name: "Carlos Méndez",
    customer_phone: "+56912345678",
    status: "paid",
    payment_status: "paid",
    payment_provider: "transbank",
    payment_intent_id: "tbk_demo_001",
    subtotal: 49900,
    shipping_cost: 0,
    tax: 0,
    total: 49900,
    shipping_address: { address: "Av. Providencia 1234", city: "Santiago", region: "Metropolitana", country: "Chile" },
    notes: null,
    metadata: null,
  },
  {
    id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    customer_email: "valentina.soto@gmail.com",
    customer_name: "Valentina Soto",
    customer_phone: null,
    status: "processing",
    payment_status: "paid",
    payment_provider: "mercadopago",
    payment_intent_id: "mp_demo_002",
    subtotal: 37800,
    shipping_cost: 3990,
    tax: 0,
    total: 41790,
    shipping_address: { address: "Los Jardines 456", city: "Ñuñoa", region: "Metropolitana", country: "Chile" },
    notes: "Entregar en portería",
    metadata: null,
  },
  {
    id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    customer_email: "rodrigo.pena@hotmail.com",
    customer_name: "Rodrigo Peña",
    customer_phone: "+56987654321",
    status: "delivered",
    payment_status: "paid",
    payment_provider: "stripe",
    payment_intent_id: "pi_demo_003",
    subtotal: 24900,
    shipping_cost: 0,
    tax: 0,
    total: 24900,
    shipping_address: { address: "Camino El Alba 789", city: "Las Condes", region: "Metropolitana", country: "Chile" },
    notes: null,
    metadata: null,
  },
  {
    id: "d4e5f6a7-b8c9-0123-def0-234567890123",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    customer_email: "carolina.lopez@empresa.cl",
    customer_name: "Carolina López",
    customer_phone: "+56956789012",
    status: "pending",
    payment_status: "pending",
    payment_provider: null,
    payment_intent_id: null,
    subtotal: 12900,
    shipping_cost: 3990,
    tax: 0,
    total: 16890,
    shipping_address: { address: "Vitacura 2345", city: "Vitacura", region: "Metropolitana", country: "Chile" },
    notes: null,
    metadata: null,
  },
  {
    id: "e5f6a7b8-c9d0-1234-ef01-345678901234",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    customer_email: "andres.morales@gmail.com",
    customer_name: "Andrés Morales",
    customer_phone: "+56923456789",
    status: "cancelled",
    payment_status: "refunded",
    payment_provider: "transbank",
    payment_intent_id: "tbk_demo_005",
    subtotal: 19900,
    shipping_cost: 0,
    tax: 0,
    total: 19900,
    shipping_address: { address: "Irarrázaval 890", city: "Macul", region: "Metropolitana", country: "Chile" },
    notes: "Cliente solicitó cancelación",
    metadata: null,
  },
];
